### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by salamaashoush** [markaren/threepp#12]
Do you plan to support macOS?
Right now you are targeting OpenGL 4.6 which is not supported on macOS , and the latest supported version is 4.1

**Comment by markaren** [comment]
MacOS is a black hole to me, so it's kinda hard for me to explicitly support it. Does it currently work if you "downgrade" to 4.1 ?
That is, change `conanfile.txt` to use 4.1.

**Comment by salamaashoush** [comment]
I tried downgrading to 4.1 and changing couple of lines of code and it works

**Comment by salamaashoush** [comment]
I created this PR you can check the code https://github.com/markaren/threepp/pull/13, also I didn't test it on other platforms after my change
