### ISSUE TITLE
Window does not resize correctly

### ISSUE THREAD

**Issue by yammelvin** [markaren/threepp#120]
Ran several demos. All has the same issue.
Rendering is fine. However, when I try to resize the window, the window does not resize correctly.
The window keeps getting bigger when I drag the mouse and stop responding to the minimize, maximize and close button.
Had to press Ctrl-C at the terminal to close the window.
I'm using Ubuntu 22.04 LTS.

**Comment by markaren** [comment]
Strange. I have not encountered this issue, so more info would be helpful.

**Comment by yammelvin** [comment]
I added a line in examples/demo.cpp to print the width, height and aspect in the canvas.OnWindowResize()
```
    canvas.onWindowResize([&](WindowSize size) {
        std::cout << "w:" << size.width << ",h:" << size.height << ",a:" << size.getAspect() << std::endl;
        camera->aspect = size.getAspect();
        camera->updateProjectionMatrix();
        renderer.setSize(size);
        handle.setPosition(canvas.getSize().width - 130, 0);
    });
```

Attached is the output.
The size keeps growing regardless of the direction of the mouse drag.
Occasionally it will suddenly jump to w:474,h:311,a:1.52412

[sizes.zip](https://github.com/markaren/threepp/files/11190125/sizes.zip)

**Comment by markaren** [comment]
As far as I know, you are the only one experiencing this. It should not be an issue on Mac and Windows.
I'm assuming you are using vcpkg to get the `glfw` library?

**Comment by yammelvin** [comment]
Yes. I am using vcpkg.

I commented the following line in Canvas.cpp:
```
// glfwSetWindowSizeCallback(window, window_size_callback);
```

Then, the window  resizes correctly.
But the canvas does not resize.

**Comment by markaren** [comment]
You are the first to raise this issue. I would think this is a screen issue rather than a OS issue, however.

A quick fix would be to set the canvas size once of course.

Could you attach a gif showing the issue in action?

**Comment by yammelvin** [comment]
![Screenshot from 2023-04-11 00-41-56](https://user-images.githubusercontent.com/4566909/230948641-15153b52-791c-4340-9a49-d93c09694b9d.png)

**Comment by yammelvin** [comment]
OK. I commented the following line in GLRenderer.cpp:
```
void GLRenderer::setSize(WindowSize size) {

    pimpl_->_size = size;

    int canvasWidth = pimpl_->_size.width * pimpl_->_pixelRatio;
    int canvasHeight = pimpl_->_size.height * pimpl_->_pixelRatio;

    std::cout << "canvasWidth:" << canvasWidth << ",canvasHeight:" << canvasHeight << ",pixelRatio:" << pimpl_->_pixelRatio << std::endl;
    //pimpl_->canvas_.setSize({canvasWidth, canvasHeight});

    this->setViewport(0, 0, size.width, size.height);
}
```

Both the window and the canvas resizes correctly. 
But the text position is wrong.
See attached screenshot.

![Screenshot from 2023-04-11 01-08-29](https://user-images.githubusercontent.com/4566909/230953726-49326c38-3642-4214-8e33-354a4f5a374b.png)

**Comment by yammelvin** [comment]
Canvas::setSize() calls glfwSetWindowSize()
```
    void setSize(WindowSize size) const {
        glfwSetWindowSize(window, size.width, size.height);
    }
```
would that not trigger the window resize event again?

**Comment by markaren** [comment]
> In demo.cpp, onWindowResize() calls renderer setSize() which calls canvas setSize() which in turn calls glfwSetWindowSize(), would that not trigger the window resize event again?

Apparantly not.
The reason it is called again has to do with the extra pixelRatio information that is passed (have not used that feature myself)

> But the text position is wrong.

In that case, the text is correct here.

**Comment by yammelvin** [comment]
My apologies. My bad.
Earlier, I commented the following line:
```
    canvas.onWindowResize([&](WindowSize size) {
        std::cout << "w:" << size.width << ",h:" << size.height << ",a:" << size.getAspect() << std::endl;
        camera->aspect = size.getAspect();
        camera->updateProjectionMatrix();
        renderer.setSize(size);
        // handle.setPosition(canvas.getSize().width - 130, 0);
    });
```
That's why the position is wrong.

Now, I've uncommented the above line
and with the following line commented in GLRenderer::SetSize
```
void GLRenderer::setSize(WindowSize size) {

    pimpl_->_size = size;

    int canvasWidth = pimpl_->_size.width * pimpl_->_pixelRatio;
    int canvasHeight = pimpl_->_size.height * pimpl_->_pixelRatio;

    std::cout << "canvasWidth:" << canvasWidth << ",canvasHeight:" << canvasHeight << ",pixelRatio:" << pimpl_->_pixelRatio << std::endl;
    // pimpl_->canvas_.setSize({canvasWidth, canvasHeight});

    this->setViewport(0, 0, size.width, size.height);
}
```

Now, everything works fine. The window and the canvas resizes correctly. Text position is correct.
Seems like the glfwSetWindowSize() does trigger the window resize event again.
See attached screenshot.


![Screenshot from 2023-04-11 00-41-56](https://user-images.githubusercontent.com/4566909/230962606-39c330a6-5f94-4494-bc3f-4b95d51b0ba5.png)

**Comment by markaren** [comment]
> Seems like the glfwSetWindowSize() does trigger the window resize event again.

Then it's possible that the beaviour is different on Linux systems. Will make a PR, and you can test it.

**Comment by markaren** [comment]
Please have a go at: https://github.com/markaren/threepp/tree/fix/window_resize

**Comment by yammelvin** [comment]
Nope. The fix does not work.

**Comment by yammelvin** [comment]
I added 4 cout lines in Canvas.cpp:
```
    void setSize(WindowSize size, bool internal) {
        if (internal) manualWindowResizeState = true;
        std::cout << "Before setting window size" << std::endl;
        glfwSetWindowSize(window, size.width, size.height);
        std::cout << "After Setting window size" << std::endl;
        if (internal) manualWindowResizeState = false;
    }
```

```
    static void window_size_callback(GLFWwindow* w, int width, int height) {
        std::cout << "window_size_callback" << std::endl;
        auto p = static_cast<Canvas::Impl*>(glfwGetWindowUserPointer(w));
        p->size_ = {width, height};
        if (!p->manualWindowResizeState && p->resizeListener) {
            std::cout << "calling listener" << std::endl;
            p->resizeListener.value().operator()(p->size_);
        }
    }
```

Output is:
```
Before setting window size
After Setting window size
window_size_callback
calling listener
Before setting window size
After Setting window size
window_size_callback
calling listener
Before setting window size
After Setting window size
window_size_callback
calling listener
. . .
```

Apparently, glfwSetWindowSize() return immediately and then the window resize callback is triggered.
therefore manualWindowResizeState is always false.

**Comment by markaren** [comment]
Try now

**Comment by yammelvin** [comment]
Nope. Still not working.

Added following couts:
```
    static void window_size_callback(GLFWwindow* w, int width, int height) {
        std::cout << "window_size_callback" << std::endl;
        auto p = static_cast<Canvas::Impl*>(glfwGetWindowUserPointer(w));
        p->size_ = {width, height};
        if (!p->manualWindowResizeState && p->resizeListener) {
            std::cout << "before calling listener" << std::endl;
            p->resizeListener.value().operator()(p->size_);
            std::cout << "after calling listener" << std::endl;
        }
        std::cout << "setting manualWindowResizeState=false" << std::endl;
        p->manualWindowResizeState = false;
    }
```    void setSize(WindowSize size, bool internal) {
        if (internal) {
            std::cout << "setting manualWindowResizeState=true" << std::endl;
            manualWindowResizeState = true;
        }
        std::cout << "before glfwSetWindowSize" << std::endl;
        glfwSetWindowSize(window, size.width, size.height);
        std::cout << "after glfwSetWindowSize" << std::endl;
    }
```

Output is:
```
window_size_callback
before calling listener
setting manualWindowResizeState=true
before glfwSetWindowSize
after glfwSetWindowSize
after calling listener
setting manualWindowResizeState=false
window_size_callback
before calling listener
setting manualWindowResizeState=true
before glfwSetWindowSize
after glfwSetWindowSize
after calling listener
setting manualWindowResizeState=false
. . .
```

**Comment by yammelvin** [comment]
I made the following changes. 
And tested working.

Added to Canvas.cpp
```
bool toSetGlfwWindowSize = true;
```

the parameter internal is not needed.
```
    void setSize(WindowSize size, bool internal) {
        if (toSetGlfwWindowSize) {
            glfwSetWindowSize(window, size.width, size.height);
        }
    }
```

```
    static void window_size_callback(GLFWwindow* w, int width, int height) {
        auto p = static_cast<Canvas::Impl*>(glfwGetWindowUserPointer(w));
        p->toSetGlfwWindowSize = false;
        p->size_ = {width, height};
        if (p->resizeListener) {
            p->resizeListener.value().operator()(p->size_);
        }
        p->toSetGlfwWindowSize = true;
    }
```

**Comment by yammelvin** [comment]
#122
