### ISSUE TITLE
Missing glad related defines using conan

### ISSUE THREAD

**Issue by josefgraus** [markaren/threepp#127]
First I wanted to thank you for this port. I'm getting up-to-speed with it fairly quickly and so far it's an enjoyable experience.

I just wanted to report a difficulty I had initially building the threepp library.
In `src\threepp\renderers\gl\GLCapabilities.cpp`, three of the defines (`GL_MAX_VERTEX_UNIFORM_VECTORS`, `GL_MAX_VARYING_VECTORS`, and `GL_MAX_FRAGMENT_UNIFORM_VECTORS`) were undefined when I first attempted to build.

I discovered this was related to the opengl version that glad was fetching by default. Apparently these aren't included in the opengl 3.3 compatibility extensions. I boosted the version up to opengl 4.6 compat and it resolved the issue. I'm pulling down glad via ConanCenter so it was fairly easy to change the recipe, but it definitely confused me for a short while. Thought I'd mention it in case others had trouble.

**Comment by markaren** [comment]
So I guess the issue is somewhat related to defaults on conan? I explicitly supported conan, but removed the extra code for that in 7ca8572ec22e40c25357ebc2e7f22bf170d1b8a0. Like with the vcpkg approach, I remember that also gave the expected results.

output from `examples/misc/test_capabilities.cpp`:
```
GLCapabilities(      
maxAnisotropy: 0     
maxTextures: 32      
maxVertexTextures: 32
maxTextureSize: 16384
maxCubemapSize: 16384
maxAttributes: 16    
maxVertexUniforms: 1024
maxVaryings: 16
maxFragmentUniforms: 1024
vertexTextures: true
maxSamples: 16
)
```

> and so far it's an enjoyable experience

👍

**Comment by markaren** [comment]
>  but I'm also hoping to support building on at least debian-based linux distros and macOS

vcpkg works great for these platforms as well :) Ubuntu 20.04, MacOS-11 and Windows runs is configured to run in the CI.

**Comment by josefgraus** [comment]
Oh I wasn't aware, haha. I'll give it a look.
