### ISSUE TITLE
How to load a urdf in my dear Imgui C++ window ?

### ISSUE THREAD

**Issue by gupta-ish** [markaren/threepp#149]
I need a urdf Loader similar to this - [https://github.com/gkjohnson/urdf-loaders](https://github.com/gkjohnson/urdf-loaders)

**Comment by markaren** [comment]
This is not in scope of the threepp library as it stands.

**Comment by markaren** [comment]
However, you could use something like pugixml to read the URDF file and do something with the information using threepp.
