### ISSUE TITLE
unresolved externals

### ISSUE THREAD

**Issue by hermannfischer** [markaren/threepp#173]
I'm very new to threepp and vcpkg. I created the library as described and all demos are working very well. Now I wanted to create my own test application in qt creator and I'm getting the following errors. I don't understand, what I am missing...

threepp.lib(Color.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z)
threepp.lib(GLProgram.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
threepp.lib(GLUniforms.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
threepp.lib(PeripheralsEventSource.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct threepp::KeyListener * * __cdecl __std_find_trivial<struct threepp::KeyListener *,unsigned __int64>(struct threepp::KeyListener * *,struct threepp::KeyListener * *,unsigned __int64)" (??$__std_find_trivial@PEAUKeyListener@threepp@@_K@@YAPEAPEAUKeyListener@threepp@@PEAPEAU01@0_K@Z)
threepp.lib(StringUtils.obj) : error LNK2001: unresolved external symbol "unsigned int const * const std::_Large_power_data" (?_Large_power_data@std@@3QBIB)

**Comment by markaren** [comment]
May I ask how your configuration looks? Which compiler are you using? Is it a C++17 compiler?

**Comment by hermannfischer** [comment]
Hey, thank you for your quick reply. I'm using Qt Creator with Qt 6.5 and the MSVC2019 64 bit. The Compiler is a c++ 17 compiler...

**Comment by hermannfischer** [comment]
I created a complete new project (non QT, Plan C++ Application) and added the libs and the includepath to the .pro file. I copied then your example from the github startpage and got these errors..

**Comment by markaren** [comment]
Are you specifying the Qt project as a C++17 project?

I'm not familiar with Qt creator, but it can load CMake projects right? Can you open the (standalone) test project from threepp directly: https://github.com/markaren/threepp/tree/master/tests/threepp_vcpkg_test ?

**Comment by hermannfischer** [comment]
Hmm. I'm not new to C++, but I'm new to QT Creator too. Perhaps I should learn some more Qt :) 
the compiler says "warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library" and I think, this could be my problem. 
Thank you very much for your help

**Comment by markaren** [comment]
Reported as resolved elsewhere.

@hermannfischer Would you mind sharing the solution?
