### ISSUE TITLE
Shadow seems to be clipped

### ISSUE THREAD

**Issue by hermannfischer** [markaren/threepp#177]
Hello... I got it working on Qt. Now I played around with some examples. In the following example the shadow seems to be clipped.
[main.cpp.txt](https://github.com/markaren/threepp/files/13031699/main.cpp.txt)

**Comment by markaren** [comment]
You likely need to increase the viewport of the underlying OrthographicCamera used by the DirectionalShadow. I think the behaviour is similar to three.js.

This part of the API is not great and you likely ned to `#include "threepp/lights/LightShadow.hpp"`
To get the camera:
```cpp
 auto shadowCamera = light->shadow->camera->as<OrthographicCamera>();
```

**Comment by hermannfischer** [comment]
Thank you very much. I try to check it, but it might take some time. But I will return here and tell you my result :)
