### ISSUE TITLE
Rendering threepp inside ImGui widget

### ISSUE THREAD

**Issue by wizard1989** [markaren/threepp#185]
Good day!

It's not an issue, but feature or advice request.

I use ImGui with lots of widgets and 2d plots. Now I want to have 3d visualisation, like threepp does.

I have tried to launch two ImGui windows in two different threads and different glfw and ImGui contexts, but, unfortunately, ImGui is using global variables and can have only one context inside application.

Is it possible to launch threepp with ImGui in another window?

If not. Could you, please, give me an advice on how to make threepp rendering inside ImGui widget like in this article: https://uysalaltas.github.io/2022/01/09/OpenGL_Imgui.html

Here is a gif of what it looks like:
https://uysalaltas.github.io/img/posts/OpenGL_Imgui/Scene%20Gif.gif

Kindest regards!

**Comment by markaren** [comment]
threepp currently does not support it directly, as ImGui needs a textureId. This id is not accessible through the API.
I did a test however, exposing the id through the Texture class (assigning the id in GLTextures).

```cpp

//....

renderer.copyFramebufferToTexture(vector, *texture);

//...

ImGui::SetNextWindowSize({static_cast<float>(textureSize), static_cast<float>(textureSize)}, 0);
ImGui::Begin("Framebuffer");

if (texture->glTexture__ > 0) {
  ImVec2 pos = ImGui::GetCursorScreenPos();
  ImGui::GetWindowDrawList()->AddImage(
          (void*) texture->glTexture__,
          ImVec2(pos.x, pos.y),
          ImVec2(pos.x+textureSize, pos.y+textureSize),
          ImVec2(0, 1),
          ImVec2(1, 0));
}

ImGui::End();
```

**Comment by markaren** [comment]
See https://github.com/markaren/threepp/commit/f87910c82906825c1612b43fd16463c6e587f5d4

**Comment by wizard1989** [comment]
Thank you!
