### ISSUE TITLE
Cmake Glfw3 installed v3.3.9 cannot be introduced

### ISSUE THREAD

**Issue by phpix** [markaren/threepp#188]
CMake prompt

CMake Error at CMakeLists. txt: 28 (find_package):

Could not find a package configuration file provided by "glfw3" with any of

The following names:

Glfw3Config.cmake

Glfw3 config. cmake

Add the installation prefix of "glfw3" to CMAKE_ PREFIX_ PATH or set

![image](https://github.com/markaren/threepp/assets/50228596/86064c9b-6de2-4a60-89fb-5c53a0a18935)

I don't know why, could you please help me explain? Thank you

**Comment by phpix** [comment]
cmake gui add entry  name ,type,value    type:path

CMAKE_PREFIX_PATH = D:/Code/threepp/vcpkg/packages

**Comment by phpix** [comment]
![image](https://github.com/markaren/threepp/assets/50228596/682750b0-176e-4380-9d0a-e0774718d22b)
The compilation time has exceeded two days, which is very troublesome

**Comment by markaren** [comment]
```
cmake . -A x64 -B build -DCMAKE_TOOLCHAIN_FILE="[path/to/vcpkg]/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Release"

cmake --build build --config Release
```

**Comment by phpix** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by phpix** [comment]
Glfw3 successfully installed version 3.3.9, but using cmakegui still prompts that it cannot be imported

# this is heuristically generated, and may not be correct
  find_package(glfw3 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE glfw)

glfw3 provides pkg-config modules:

    # A multi-platform library for OpenGL, window and input
    glfw3

CMake Error at CMakeLists.txt:36 (add_library):
  add_library cannot create ALIAS target "glfw::glfw" because target "glfw"
  is imported but not globally visible.
![image](https://github.com/markaren/threepp/assets/50228596/d1c372b4-6c65-446b-87d9-b44db5d58eb0)
Could you please assist in identifying the cause of the problem? Thank you!

**Comment by phpix** [comment]
This project is a small mistake made by Camke, and the subsequent errors cannot be seen. CMake is very upset about it! Three minutes for a small problem, ten minutes for a big problem. Continuously solving compatibility issues with VCPKG package versions, compiling for three days, but no 3D model display yet!

**Comment by phpix** [comment]
Your project is very beautiful, just because you are not proficient in using VCPKG compilation, which makes the compilation so difficult! I hope to see the 3D model displayed smoothly!

**Comment by phpix** [comment]
Configure with colleagues and solve problems perfectly. Conflict between glfw3 and glfw aliases caused! Thank you for your help
