### ISSUE TITLE
GLFW_KEY_ESCAPE close window no matter what

### ISSUE THREAD

**Issue by doubledong94** [markaren/threepp#195]
in Canvas.cpp, key_callback close the window when recieve escape key, there is no way to disable this. please make this optional, thanks for your work.

**Comment by markaren** [comment]
May I ask for the use case? In what setting is that not what you want?

**Comment by doubledong94** [comment]
my case is that i need multi imgui windows in my project, the windows open and close by hotkeys, and i want to use the escape key to be the uni-hotkey for closing all windows except the main one, does this need sounds reasonable?

**Comment by markaren** [comment]
Very reasonable. I'll figure something out

**Comment by markaren** [comment]
The open PR makes this possible.

```cpp
Canvas canvas("threepp demo", {{"aa", 4}, {"exitOnKeyEscape", false}});
```

**Comment by doubledong94** [comment]
Thanks, the work is nicely done!
