### ISSUE TITLE
depth test not working with custom projection matrix 

### ISSUE THREAD

**Issue by longsamaa** [markaren/threepp#208]
I already have a projection matrix. For each render I want to use threepp to render the model with that projection matrix. I reassigned the camera's projection matrix like this: 
```cpp
main_camera->projectionMatrix = matrix;
main_render->render(*main_scene, *main_camera);
```

![Untitled](https://github.com/markaren/threepp/assets/61380706/175599ea-ce16-452c-bf47-648481cfd867)

My model was rendering properly on screen. But it seems the depth test doesn't work. Is there any way for me to fix this ? 
Thanks for help!

**Comment by markaren** [comment]
Are you sure the issue is related the `projectionMatrix`? I can't immidiatly see anything in the code that should affect this based on that value. Could it be the material settings? How does it look with the `PerspectiveCamera`?

**Comment by longsamaa** [comment]
> Are you sure the issue is related the `projectionMatrix`? I can't immediately see anything in the code that should affect this based on that value. Could it be the material settings? How does it look with the `PerspectiveCamera`?
I just reassigned the projection matrix to the camera. Let threepp render my model like this:
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/
Do I need to edit anything to make threepp render correctly?
Thank you!

**Comment by longsamaa** [comment]
yep sure!! 
i use threepp with maplibre native with my custom layer. 
I initialize scene and camera in my layer like this: 
main_render = std::make_shared<threepp::GLRenderer>(window_size); // size of maplibre native window 
main_render->autoClear = false; 
main_render->checkShaderErrors = true; 
main_camera = std::make_shared<threepp::Camera>(); 
main_scene = threepp::Scene::create(); 
main_obj = loader.load("\\data\\models\\collada\\youbot.dae");
main_obj->rotate(M_PI * 0.5); 
and when rendering I use this: 
 auto matrix = par.matrix // matrix of tile maplibre
 threepp::Matrix4 m; 
 m.fromArray(matrix.data()); 
 main_render->resetState(); 
 main_camera->projectionMatrix = m;
 main_render->render(*main_scene, *main_camera);
My model has the correct position on the tile. very interesting but it seems the dept test has an error like this: 
![image](https://github.com/markaren/threepp/assets/61380706/6ba4cb8c-e1c9-4c3c-b759-687004ac29b7)

**Comment by markaren** [comment]
You have `autoClear = false`, but I don't see any clearing of the threepp rendering?

**Comment by longsamaa** [comment]
yeah I tried clearing of the threepp rendering before render: 
main_render->clearDepth(); 
main_render->clearStencil();
But it still doesn't work

**Comment by markaren** [comment]
Could you share more complete example code (or complete proeject) that highlights the issue?

**Comment by longsamaa** [comment]
Yes, how can I share source code with you?

**Comment by markaren** [comment]
You could zip the project to me by mail (visible on my profile)

**Comment by longsamaa** [comment]
sorry for the late reply!!. 
I get a error depth when when I use threepp with 1 available gl context. When i use Threepp::Canvas to create opengl context then threepp renders correctly.

**Comment by markaren** [comment]
Are you saying the issue was related to using a custom Window/OpenGL context?

Might I ask what you used?

**Comment by longsamaa** [comment]
tks for help!.
 I can fix it by turning off glCullface when render. 
 My scene can render correctly. Nice project!!
