### ISSUE TITLE
why the r129 of three.js is mentioned in the homepage

### ISSUE THREAD

**Issue by asmwarrior** [markaren/threepp#214]
Yesterday, I post a message in the wx forum:

[threepp(a three.js 3D library ported to C++) works with wxWidgets now](https://forums.wxwidgets.org/viewtopic.php?f=10&t=51046)

One of the admin commented that why the r129 is mentioned, this version is about 3 years ago. Any ideas? Thanks.

**Comment by markaren** [comment]
r129 was the current version when I started the port, and the very core of the library is pretty close to that version.  Some additions that came later like `CapsuleGeometry` have been added though.  I value improving the usability of the library and implementing missing features over trying to keep up with the three.js version (Which in practice is probably impossible as there would be constant changes to be made).

**Comment by asmwarrior** [comment]
OK, thanks for the explanation. Keep up the good work!
