### ISSUE TITLE
How to draw a circle shape point instead of the default rectangle shape point by a custom shader

### ISSUE THREAD

**Issue by asmwarrior** [markaren/threepp#217]
Hi, this is the question asked by myself, when I draw a point, it shows in a rectangle shape.

I just searched on the internet, and found that the shape can be tweaked by the segment shader, see this link:

[Shape for points - Questions - three.js forum](https://discourse.threejs.org/t/shape-for-points/1869)
And the solution is here:
[Drawing anti-aliased circular points using OpenGL/WebGL - A Circular Reference](https://www.desultoryquest.com/blog/drawing-anti-aliased-circular-points-using-opengl-slash-webgl/)

I can manually change the shader content in the file: `data/shaders/ShaderLib/points_frag.glsl`

But what if I need to use a customized shader by myself? I mean if I don't want to change the above mentioned shader file, but use a customized one, how can I do it?

Thanks.

**Comment by markaren** [comment]
Three.js and threpp provides `RawShaderMaterial` for such a use-case. See examples in `/shaders`.
Alternatively, use a texture.

**Comment by asmwarrior** [comment]
> Three.js and threpp provides `RawShaderMaterial` for such a use-case. See examples in `/shaders`. Alternatively, use a texture.

OK, thanks for the reply. I have just read the source code of the `examples/shaders/raw_shader.cpp`, it does use a customized shader code, I will test it later.

**Comment by asmwarrior** [comment]
Here is the patch to show the circle shape points:

~~~~
diff --git a/examples/shaders/raw_shader.cpp b/examples/shaders/raw_shader.cpp
index e950d78..f0ee4f8 100644
--- a/examples/shaders/raw_shader.cpp
+++ b/examples/shaders/raw_shader.cpp
@@ -21,13 +21,13 @@ int main() {
     auto camera = PerspectiveCamera::create(60, canvas.aspect(), 1, 10);
     camera->position.z = 2;
 
-    int triangles = 1000;
+    int points = 10;
     std::vector<float> positions;
-    positions.reserve(triangles * 3);
+    positions.reserve(points * 3);
     std::vector<float> colors;
-    colors.reserve(triangles * 4);
+    colors.reserve(points * 4);
 
-    for (int i = 0; i < triangles; i++) {
+    for (int i = 0; i < points; i++) {
         positions.emplace_back(math::randFloat() - .5f);
         positions.emplace_back(math::randFloat() - .5f);
         positions.emplace_back(math::randFloat() - .5f);
@@ -49,8 +49,8 @@ int main() {
     material->side = Side::Double;
     material->transparent = true;
 
-    auto mesh = Mesh::create(geometry, material);
-    scene->add(mesh);
+    auto pointObject = Points::create(geometry, material);
+    scene->add(pointObject);
 
     canvas.onWindowResize([&](WindowSize size) {
         camera->aspect = size.aspect();
@@ -62,7 +62,7 @@ int main() {
     canvas.animate([&]() {
         float t = clock.getElapsedTime();
 
-        mesh->rotation.y = t * 0.5f;
+        pointObject->rotation.y = t * 0.5f;
         material->uniforms->at("time").setValue(t * 5);
 
         renderer.render(*scene, *camera);
@@ -85,6 +85,7 @@ std::string vertexSource() {
                    vPosition = position;
                    vColor = color;
                    gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
+                   gl_PointSize = 10.0;
                })";
 }
 
@@ -102,5 +103,9 @@ std::string fragmentSource() {
                    vec4 color = vec4( vColor );
                    color.r += sin( vPosition.x * 10.0 + time ) * 0.5;
                    gl_FragColor = color;
+                   vec2 circCoord = 2.0 * gl_PointCoord - 1;
+                   if (dot(circCoord, circCoord) > 1) {
+                       discard;
+                   }
                 })";
 }
~~~~

And here is the screen shots:

![image](https://github.com/markaren/threepp/assets/561818/0383cb6d-50cf-4505-966e-a40d23ed164f)
