### ISSUE TITLE
cmake file typo option(THREEPP_WITH_GLFW "Build GLFW frontend" ON)

### ISSUE THREAD

**Issue by asmwarrior** [markaren/threepp#218]
Is it should be below:

`option(THREEPP_WITH_GLFW "Build with GLFW frontend" ON)`

Note a "with" is needed here.

**Comment by markaren** [comment]
IMO it's pracically the same

**Comment by asmwarrior** [comment]
Oh, I think they are different.

In my opinion, when you say: "Build with GLFW frontend", this means you want to link the glfw library when building the threepp, when you say: "Build GLFW frontend", this means you want to build the glfw library.

You already has some statement using "with", see below:

https://github.com/markaren/threepp/blob/9b99e09ce465608e1bf43e2539b09a007543a07d/CMakeLists.txt#L9-L11
