### ISSUE TITLE
Error: This binary only supports the Null platform

### ISSUE THREAD

**Issue by seanbutler** [markaren/threepp#251]
the title explains it all really.

on ubuntu 23.10, razer laptop w/ nvidia mobile chipset. driver v. 535.161.07

when i compile the lib using the instructions from the  read me [here](https://github.com/markaren/threepp?tab=readme-ov-file#how-to-build). most/all the examples give the above error message. 

does anyone have any thoughts/advice?
thanks.

**Comment by seanbutler** [comment]
this worked, thanks for your help!

cmake --build build -DTHREEPP_USE_EXTERNAL_GLFW=ON
shall i update the README and submit a pull req?

**Comment by markaren** [comment]
It is likely a bug where the default configuration is mismatched on the linux platform. Using external glfw should not be required. An eventual PR should fix the configuration problem.

**Comment by elricmann** [comment]
To touch base on this, I've encountered the same issue, would be helpful to have this highlighted in the README as a side note like @seanbutler mentioned, at least until the changes have been reflected.

The following changes worked for my setup:

```
$ cmake -S . -B build -DTHREEPP_USE_EXTERNAL_GLFW=ON
$ cmake --build build
```

Great work, thanks!

**Comment by markaren** [comment]
I could add a note that it is possible to use external glfw as an option.

As for this issue, I really need someone with a desktop Linux system to figure out how to get it working with the bundled glfw installation to close this issue.

**Comment by Choons** [comment]
Just had same issue on my Ubuntu machine and the instructions Eric gave above worked for me too.

**Comment by markaren** [comment]
Ok, the way I understand this now is that Linux needs either X11 or wayland, and macos needs cocoa.

I currently do,
```
set(GLFW_BUILD_COCOA OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_WAYLAND OFF CACHE BOOL "" FORCE)
if (THREEPP_EMBEDDED_GLFW_WITH_X11)
    set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)
else ()
    set(GLFW_BUILD_X11 OFF CACHE BOOL "" FORCE)
endif ()
```

I should propably just remove this from the CMake settings, and let users set (override default) this directly as options.

**Comment by markaren** [comment]
Need Linux and MacOS users to verify change.
