### ISSUE TITLE
Consider using SDL2

### ISSUE THREAD

**Issue by markaren** [markaren/threepp#79]
Will investigate whether or not SDL2 is a better fit for threepp

**Comment by markaren** [comment]
Closing for now. Might re-visit in the future.

**Comment by markaren** [comment]
SDL2 seems like a viable option:

![image](https://github.com/markaren/threepp/assets/6005031/97f41283-7f1d-4825-9350-764619cc0a5b)

Still not sure if I should replace GLFW support both.

**Comment by Mizux** [comment]
note: SDL2 is relatively well supported with emscripten (as well as opengles2 -> webgl) so we could use threepp to generate a wasm library i.e. threeppjs :clown_face:

ps: I' m currently looking for a threejs like library but in C++ to target native build and browser (emscripten) so threepp seems really promising !

**Comment by markaren** [comment]
Interesting @Mizux . As you can see in #158, I have a solution where either SDL2 or GLFW3 can be used. I have been questioning whether the solution is worth the attention/extra complexity.

**Comment by markaren** [comment]
Closing as the current solution works with emscripten and it is possible for users to supply their own window (with some effort, however, but without changing the library)
